import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark, neobrutalism } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: [neobrutalism],
        variables: {
          colorBackground: "#124949",
          colorText: "#FFFFFF",
          colorInputText: "#000000",
          colorPrimary: "#107361",
          colorTextOnPrimaryBackground: "#fff",
          colorDanger: "#FF0000",
          colorNeutral: "#000000",
          colorSuccess: "#00FF00",
          fontSize: "1rem",
          fontFamily: inter.className,

          // colorTextOnPrimaryBackground: "#FFFFFF",
          // colorDanger: "#FF0000",
          // colorNeutral: "#000000",
          // colorSuccess: "#00FF00",
        },

        // signIn: {
        //   variables: {
        //     colorBackground: "#124949",
        //     colorText: "#FFFFFF",
        //     colorInputText: "#000000",
        //     colorPrimary: "#107361",
        //     colorTextOnPrimaryBackground: "#FFFFFF",
        //     colorDanger: "#FF0000",
        //     colorNeutral: "#000000",
        //     colorSuccess: "#00FF00",
        //   },
        // },
      }}
    >
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
